"""Template explanations. These are not generated by BERT."""

from __future__ import annotations

from backend.services.linguistic_detector import LinguisticIssue
from backend.services.llm_analyzer import LlmReasoningResult

TYPE_EXPLANATIONS = {
    "lexical": (
        "Unclear or overloaded words make this requirement hard to implement consistently."
    ),
    "syntactic": (
        "The sentence structure can be read in more than one way."
    ),
    "semantic": (
        "The meaning of this requirement can be interpreted in different ways."
    ),
    "syntax": (
        "The wording is structurally unclear or incomplete as a formal requirement."
    ),
    "pragmatic": (
        "This requirement depends on unstated context, assumptions, or expectations."
    ),
    "clean": (
        "Stage A classified this requirement as clean, so Stage B did not assign "
        "an ambiguity type."
    ),
}


def explain(
    requirement: str,
    classification: str,
    ambiguity_type: str | None,
    type_source: str | None = None,
    overall_status: str | None = None,
    issues: list[LinguisticIssue] | None = None,
    llm: LlmReasoningResult | None = None,
) -> str:
    issues = issues or []
    primary = issues[0] if issues else None
    type_name = ambiguity_type or (primary.ambiguity_type if primary else None)
    llm_note = _llm_note(llm)

    if primary is not None:
        ml_note = (
            f"BERT Stage A predicted {classification}; that label is preserved. "
            if classification != "unavailable"
            else "BERT was unavailable. "
        )
        stage_b_note = ""
        if type_source == "hybrid":
            stage_b_note = (
                "Stage B produced a sentence-level type, but the phrase-specific "
                "linguistic finding is used for the final type. "
            )
        elif type_source == "linguistic" and classification != "ambiguous":
            stage_b_note = "Stage B did not run because Stage A did not predict Ambiguous. "
        return (
            f"{ml_note}{stage_b_note}"
            f"A linguistic check flagged '{primary.phrase}' as "
            f"{primary.ambiguity_type} ambiguity. {primary.reason}{llm_note}"
        )

    if llm and llm.available and llm.is_ambiguous and llm.explanation:
        ml_note = (
            f"BERT Stage A predicted {classification}; that label is preserved. "
            if classification != "unavailable"
            else "BERT was unavailable. "
        )
        return f"{ml_note}An LLM reasoning layer identified contextual ambiguity. {llm.explanation}"

    if classification == "clean" or overall_status == "clean":
        return (
            f"{TYPE_EXPLANATIONS['clean']} The wording looks testable as written. "
            "A conservative rewrite is still offered if you want tighter phrasing."
            f"{llm_note}"
        )

    key = type_name or "semantic"
    return TYPE_EXPLANATIONS.get(key, TYPE_EXPLANATIONS["semantic"]) + llm_note


def _llm_note(llm: LlmReasoningResult | None) -> str:
    if llm is None or not llm.available:
        return ""
    if llm.is_ambiguous and llm.explanation:
        return f" The LLM reasoning layer independently agreed there is ambiguity. {llm.explanation}"
    if llm.is_ambiguous is False:
        return " The LLM reasoning layer did not find additional ambiguity."
    return ""
